#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════
# AlgoTrendy Metrics API - HTTPS Setup Script
# ═══════════════════════════════════════════════════════════════════════════
#
# This script:
# 1. Installs nginx and certbot
# 2. Configures reverse proxy for metrics API
# 3. Obtains SSL certificate from Let's Encrypt
# 4. Sets up auto-renewal
#
# Usage:
#   ./setup_metrics_https.sh <domain> <api_key>
#
# Example:
#   ./setup_metrics_https.sh metrics.algotrendy.com my-secret-api-key-123
#
# Prerequisites:
# - Domain DNS must point to this server's IP
# - Port 80 and 443 must be open in firewall
# - Run as root or with sudo
# ═══════════════════════════════════════════════════════════════════════════

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log() { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
error() { echo -e "${RED}[✗]${NC} $1"; exit 1; }

# ═══════════════════════════════════════════════════════════════════════════
# ARGUMENTS
# ═══════════════════════════════════════════════════════════════════════════

DOMAIN="${1:-metrics.algotrendy.com}"
API_KEY="${2:-$(openssl rand -hex 32)}"

echo "═══════════════════════════════════════════════════════════════"
echo " AlgoTrendy Metrics API - HTTPS Setup"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo " Domain:  $DOMAIN"
echo " API Key: ${API_KEY:0:8}...${API_KEY: -8}"
echo ""
echo "═══════════════════════════════════════════════════════════════"

# ═══════════════════════════════════════════════════════════════════════════
# PREFLIGHT CHECKS
# ═══════════════════════════════════════════════════════════════════════════

log "Running preflight checks..."

# Check root
if [ "$EUID" -ne 0 ]; then
    error "Please run as root (sudo ./setup_metrics_https.sh ...)"
fi

# Check metrics API is running
if ! curl -s http://127.0.0.1:9000/health > /dev/null 2>&1; then
    warn "Metrics API not responding on port 9000"
    warn "Make sure metrics_api_readonly.py is running"
fi

# ═══════════════════════════════════════════════════════════════════════════
# INSTALL DEPENDENCIES
# ═══════════════════════════════════════════════════════════════════════════

log "Installing nginx and certbot..."

apt-get update -qq
apt-get install -y -qq nginx certbot python3-certbot-nginx

# ═══════════════════════════════════════════════════════════════════════════
# CONFIGURE NGINX
# ═══════════════════════════════════════════════════════════════════════════

log "Configuring nginx..."

# Create certbot webroot
mkdir -p /var/www/certbot

# Create nginx config (without SSL first for certbot)
cat > /etc/nginx/sites-available/metrics-api << 'NGINX_CONF'
# AlgoTrendy Metrics API - Initial config (pre-SSL)
server {
    listen 80;
    server_name DOMAIN_PLACEHOLDER;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 200 'Metrics API - Waiting for SSL setup';
        add_header Content-Type text/plain;
    }
}
NGINX_CONF

# Replace placeholder with actual domain
sed -i "s/DOMAIN_PLACEHOLDER/$DOMAIN/g" /etc/nginx/sites-available/metrics-api

# Enable site
ln -sf /etc/nginx/sites-available/metrics-api /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true

# Test and reload nginx
nginx -t
systemctl reload nginx

log "Nginx configured (HTTP only)"

# ═══════════════════════════════════════════════════════════════════════════
# OBTAIN SSL CERTIFICATE
# ═══════════════════════════════════════════════════════════════════════════

log "Obtaining SSL certificate from Let's Encrypt..."

# Open firewall ports if ufw is active
if command -v ufw &> /dev/null && ufw status | grep -q "Status: active"; then
    ufw allow 80/tcp
    ufw allow 443/tcp
    log "Firewall ports 80 and 443 opened"
fi

# Get certificate
certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos --email admin@algotrendy.com --redirect

log "SSL certificate obtained"

# ═══════════════════════════════════════════════════════════════════════════
# UPDATE NGINX WITH FULL CONFIG
# ═══════════════════════════════════════════════════════════════════════════

log "Updating nginx with full secure config..."

cat > /etc/nginx/sites-available/metrics-api << NGINX_FULL
# AlgoTrendy Metrics API - Secure Reverse Proxy
# Auto-generated by setup_metrics_https.sh

limit_req_zone \$binary_remote_addr zone=metrics_limit:10m rate=10r/s;

server {
    listen 80;
    server_name $DOMAIN;

    location / {
        return 301 https://\$server_name\$request_uri;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}

server {
    listen 443 ssl http2;
    server_name $DOMAIN;

    # SSL (managed by certbot)
    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;

    # Rate limiting
    limit_req zone=metrics_limit burst=20 nodelay;

    # Health check (no auth)
    location = /health {
        proxy_pass http://127.0.0.1:9000/health;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }

    # Protected endpoints
    location / {
        # API Key validation
        if (\$http_authorization != "Bearer $API_KEY") {
            return 403 '{"error": "Forbidden", "message": "Invalid API key"}';
        }

        # CORS
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;

        if (\$request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type';
            add_header 'Access-Control-Max-Age' 86400;
            return 204;
        }

        # Proxy to metrics API
        proxy_pass http://127.0.0.1:9000;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_connect_timeout 10s;
        proxy_read_timeout 30s;
    }

    access_log /var/log/nginx/metrics-api-access.log;
    error_log /var/log/nginx/metrics-api-error.log;
}
NGINX_FULL

# Test and reload
nginx -t
systemctl reload nginx

log "Nginx configured with SSL and API key auth"

# ═══════════════════════════════════════════════════════════════════════════
# SAVE API KEY
# ═══════════════════════════════════════════════════════════════════════════

log "Saving API key..."

# Save to file (readable only by root)
echo "$API_KEY" > /opt/algotrendy/.metrics_api_key
chmod 600 /opt/algotrendy/.metrics_api_key

# ═══════════════════════════════════════════════════════════════════════════
# VERIFICATION
# ═══════════════════════════════════════════════════════════════════════════

log "Verifying setup..."

echo ""
echo "Testing endpoints:"
echo ""

# Test health (no auth)
HEALTH=$(curl -s "https://$DOMAIN/health" 2>&1)
echo "  /health (no auth): $HEALTH"

# Test protected endpoint without auth (should fail)
NOAUTH=$(curl -s "https://$DOMAIN/broker/status" 2>&1)
echo "  /broker/status (no auth): $NOAUTH"

# Test protected endpoint with auth (should work)
WITHAUTH=$(curl -s -H "Authorization: Bearer $API_KEY" "https://$DOMAIN/broker/status" 2>&1 | head -c 100)
echo "  /broker/status (with auth): ${WITHAUTH}..."

# ═══════════════════════════════════════════════════════════════════════════
# SUMMARY
# ═══════════════════════════════════════════════════════════════════════════

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo " Setup Complete!"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo " Metrics API URL:  https://$DOMAIN"
echo " API Key:          $API_KEY"
echo ""
echo " Key saved to:     /opt/algotrendy/.metrics_api_key"
echo ""
echo " Next steps:"
echo " 1. Set Supabase environment variable:"
echo "    VPS_METRICS_ENDPOINT=https://$DOMAIN"
echo ""
echo " 2. Set Supabase secret for API key:"
echo "    PROXY_API_KEY=$API_KEY"
echo ""
echo " 3. Test from your machine:"
echo "    curl -H 'Authorization: Bearer $API_KEY' https://$DOMAIN/health"
echo ""
echo "═══════════════════════════════════════════════════════════════"
